tasks:
    path: /tasks
    controller: App\Controller\TaskController::index

# Ruta para el registro de Usuarios
register:
    path: /registro
    controller: App\Controller\UserController::register
