# ruta para el indice muestra todas las tareas
tasks:
    path: /
    controller: App\Controller\TaskController::index
# Ruta para mostrar el detalle de cada tarea
task_detail:
    path: /tarea{id}
    controller: App\Controller\TaskController::detail
# Ruta para crear una tarea
task_creation:
    path: /crear-tarea
    controller: App\Controller\TaskController::creation

# Ruta para el registro de Usuarios
register:
    path: /registro
    controller: App\Controller\UserController::register

# Ruta para el login 
login:
    path: /login
    controller: App\Controller\UserController::login

# Ruta para el logout
logout:
    path: /logout
    
